services:
  fastapi:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - fastapi-network

  pg_database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi-network

volumes:
  pgdata:

networks:
  fastapi-network:
    driver: bridge